DEFRA/epr-regulator-service

pipelines/ci_pipeline.yaml, pipelines/deployment-pipeline.yaml
Change the CI Pipeline and Deployment Pipeline to include endpoint to defra for GitHub Fixed [AB#360017](https://dev.azure.com/defragovuk/67a63f24-5d0d-4c35-9d23-885593eb7354/_workitems/edit/360017)
=> Pipeline endpoint change to defra

src/EPR.RegulatorService.Frontend.Web/Resources/Views/Shared/Partials/_RegistrationResubmissionDetails.cy.resx, src/EPR.RegulatorService.Frontend.Web/Resources/Views/Shared/Partials/_RegistrationResubmissionDetails.en.resx, src/EPR.RegulatorService.Frontend.Web/Resources/Views/Shared/Partials/_RegistrationSubmissionDetails.cy.resx, src/EPR.RegulatorService.Frontend.Web/Resources/Views/Shared/Partials/_RegistrationSubmissionDetails.en.resx, src/EPR.RegulatorService.Frontend.Web/Views/Shared/Partials/_RegistrationResubmissionDetails.cshtml, src/EPR.RegulatorService.Frontend.Web/Views/Shared/Partials/_RegistrationSubmissionDetails.cshtml
[AB#386412](https://dev.azure.com/defragovuk/67a63f24-5d0d-4c35-9d23-885593eb7354/_workitems/edit/386412)-organisation period missing text is fixed
=> AB#386412-organisation period missing text is fixed

src/EPR.RegulatorService.Frontend.Web/Controllers/Submissions/SubmissionsController.cs, src/EPR.RegulatorService.Frontend.Web/Resources/Views/Shared/Partials/_ResubmissionDetails.en.resx, src/EPR.RegulatorService.Frontend.Web/Resources/Views/Shared/Partials/_SubmissionDetails.en.resx, src/EPR.RegulatorService.Frontend.Web/ViewModels/Submissions/SubmissionDetailsViewModel.cs, src/EPR.RegulatorService.Frontend.Web/Views/Shared/Partials/_ResubmissionDetails.cshtml, src/EPR.RegulatorService.Frontend.Web/Views/Shared/Partials/_SubmissionDetails.cshtml
https://dev.azure.com/defragovuk/RWD-CPR-EPR4P-ADO/_workitems/edit/387352
=> 387352: Include submission period in PoM submissions details page

src/EPR.RegulatorService.Frontend.UnitTests/Usings.cs, src/EPR.RegulatorService.Frontend.UnitTests/Web/Controllers/CookiesControllerTests.cs, src/EPR.RegulatorService.Frontend.UnitTests/Web/Controllers/RegulatorEnrolmentControllerTests.cs, src/EPR.RegulatorService.Frontend.UnitTests/Web/Cookies/CookieServiceTests.cs, src/EPR.RegulatorService.Frontend.UnitTests/Web/ViewComponents/CookieBannerViewComponentTests.cs, src/EPR.RegulatorService.Frontend.Web/EPR.RegulatorService.Frontend.Web.csproj, src/EPR.RegulatorService.Frontend.Web/Extensions/ServiceProviderExtension.cs
=> Sonar Qube clean-up. AB#357649

src/EPR.RegulatorService.Frontend.Web/Views/Shared/_Layout.cshtml
400117: Google Analytics tag manager script update
=> 400117: Google Analytics tag manager script update AB#400117

src/EPR.RegulatorService.Frontend.Web/Resources/Views/Shared/Partials/_RegistrationResubmissionDetails.cy.resx, src/EPR.RegulatorService.Frontend.Web/Resources/Views/Shared/Partials/_RegistrationResubmissionDetails.en.resx, src/EPR.RegulatorService.Frontend.Web/Resources/Views/Shared/Partials/_RegistrationResubmissionDetails.resx, src/EPR.RegulatorService.Frontend.Web/Resources/Views/Shared/Partials/_RegistrationSubmissionDetails.cy.resx, src/EPR.RegulatorService.Frontend.Web/Resources/Views/Shared/Partials/_RegistrationSubmissionDetails.en.resx, src/EPR.RegulatorService.Frontend.Web/Resources/Views/Shared/Partials/_RegistrationSubmissionDetails.resx, src/EPR.RegulatorService.Frontend.Web/ViewModels/Registrations/RegistrationDetailsViewModel.cs, src/EPR.RegulatorService.Frontend.Web/Views/Shared/Partials/_RegistrationResubmissionDetails.cshtml, src/EPR.RegulatorService.Frontend.Web/Views/Shared/Partials/_RegistrationSubmissionDetails.cshtml
[AB#421782](https://dev.azure.com/defragovuk/67a63f24-5d0d-4c35-9d23-885593eb7354/_workitems/edit/421782)
=> Removed Submitted On Time (for RC4)

src/EPR.RegulatorService.Frontend.Web/appsettings.json
remove GA TAG id from app settings and use epr settings solution to set the values
=> remove GA TAG id from app settings and use epr settings solution to set the values

src/EPR.RegulatorService.Frontend.UnitTests/Web/Controllers/RegistrationSubmissionsControllerTests.cs, src/EPR.RegulatorService.Frontend.Web/Controllers/RegistrationSubmissions/RegistrationSubmissionsController.cs
User story #452779 has also been completed as part of this PR
=> [feature/452771: Redirect user to org details page]

src/EPR.RegulatorService.Frontend.UnitTests/Web/Controllers/RegistrationSubmissionsControllerTests.cs, src/EPR.RegulatorService.Frontend.Web/Controllers/RegistrationSubmissions/RegistrationSubmissionsController.cs
Another PR for the POST endpoints
=> [feature/452771: Redirect user to org details page POST]

src/EPR.RegulatorService.Frontend.Core/Models/RegistrationSubmissions/RegistrationSubmissionOrganisationDetails.cs, src/EPR.RegulatorService.Frontend.Core/Models/RegistrationSubmissions/RegistrationSubmissionOrganisationSubmissionSummaryDetails.cs, src/EPR.RegulatorService.Frontend.Core/Services/FacadeService.cs, src/EPR.RegulatorService.Frontend.Core/Services/IFacadeService.cs, src/EPR.RegulatorService.Frontend.Core/Services/MockedFacadeService.cs, src/EPR.RegulatorService.Frontend.UnitTests/Core/Services/FacadeServiceTests.cs, src/EPR.RegulatorService.Frontend.UnitTests/Web/Controllers/RegistrationSubmissionsControllerTests.cs, src/EPR.RegulatorService.Frontend.Web/Controllers/RegistrationSubmissions/RegistrationSubmissionsController.cs, src/EPR.RegulatorService.Frontend.Web/Controllers/RegistrationSubmissions/RegistrationSubmissionsController_part.cs, src/EPR.RegulatorService.Frontend.Web/ViewModels/RegistrationSubmissions/PaymentDetailsViewModel.cs, src/EPR.RegulatorService.Frontend.Web/appsettings.json
456918 Added code changes for GetRegistrationSubmissionOrganisationDetails
=> 456918 Added code changes for GetRegistrationSubmissionOrganisationDetails

src/EPR.RegulatorService.Frontend.UnitTests/Web/Attributes/DateValidationAttributeTests.cs, src/EPR.RegulatorService.Frontend.Web/Attributes/DateValidationAttribute.cs, src/EPR.RegulatorService.Frontend.Web/Controllers/RegistrationSubmissions/RegistrationSubmissionsController.cs, src/EPR.RegulatorService.Frontend.Web/Controllers/RegistrationSubmissions/RegistrationSubmissionsController_part.cs
Update  year rule. Year should be >= 1000 and < 9999
=> Update  year rule. Year should be >= 1000 and < 9999

src/EPR.RegulatorService.Frontend.UnitTests/Web/Controllers/RegistrationSubmissionsControllerTests.cs, src/EPR.RegulatorService.Frontend.Web/Controllers/RegistrationSubmissions/RegistrationSubmissionsController.cs
Added code to fix the issue Refusing a queried application displays error page
=> Added code to fix the issue Refusing a queried application displays error page

src/EPR.RegulatorService.Frontend.Web/Views/Shared/Partials/_RegistrationSubmissionActionButtons.cshtml
Added code to handle action buttons for RegistrationSubmissionStatus.Pending
=> Added code to handle action buttons for RegistrationSubmissionStatus.Pending

src/EPR.RegulatorService.Frontend.Web/Views/Shared/Partials/_RegistrationSubmissionActionButtons.cshtml
Remove Query and Refuse buttons for Pending Submissions.
Show Cancelled button for Granted submissions
=> Change Action Button display to remove Query and Refused options

pipelines/deployment-pipeline.yaml, src/EPR.RegulatorService.Frontend.Web/Views/RegistrationSubmissions/Partials/_RegistrationSubmissionsFilters.cshtml
Minor code changes to remove Queried and Refused submission statuses on registrations landing page
=> Minor code changes to remove Queried and Refused submission statuses on registrations landing page

src/EPR.RegulatorService.Frontend.Web/Views/RegistrationSubmissions/Partials/_RegistrationSubmissionsFilters.cshtml
Minor code changes to remove  the filter options Queried and Refused submission statuses on registrations landing page
=> Minor code changes to remove  Queried and Refused submission statuses on registrations landing page

src/EPR.RegulatorService.Frontend.Web/Views/RegistrationSubmissions/Partials/_RegistrationSubmissionsFilters.cshtml, src/EPR.RegulatorService.Frontend.Web/Views/Shared/Partials/_RegistrationSubmissionActionButtons.cshtml
Rollback code changes for Filter options and Action Buttons
=> Rollback code changes for Filter options and Action Buttons

src/EPR.RegulatorService.Frontend.Web/Controllers/Submissions/SubmissionsController.cs, src/EPR.RegulatorService.Frontend.Web/Resources/SharedResources.cy.resx, src/EPR.RegulatorService.Frontend.Web/Resources/SharedResources.en.resx, src/EPR.RegulatorService.Frontend.Web/Views/Shared/Components/PackagingCompliancePaymentDetails/Default.cshtml, src/EPR.RegulatorService.Frontend.Web/Views/Shared/Components/PackagingProducerPaymentDetails/Default.cshtml
Added code for PackagingProducerPaymentDetails view
=> Added code for PackagingProducerPaymentDetails view

src/EPR.RegulatorService.Frontend.Core/Models/RegistrationSubmissions/RegulatorDecisionRequest.cs, src/EPR.RegulatorService.Frontend.UnitTests/Web/Controllers/RegistrationSubmissionsControllerTests.cs, src/EPR.RegulatorService.Frontend.Web/Controllers/RegistrationSubmissions/RegistrationSubmissionsController.cs, src/EPR.RegulatorService.Frontend.Web/Controllers/RegistrationSubmissions/RegistrationSubmissionsController_part.cs, src/EPR.RegulatorService.Frontend.Web/Resources/Views/RegistrationSubmissions/GrantRegistrationSubmission.cy.resx, src/EPR.RegulatorService.Frontend.Web/Resources/Views/RegistrationSubmissions/GrantRegistrationSubmission.en.resx, src/EPR.RegulatorService.Frontend.Web/ViewModels/RegistrationSubmissions/GrantRegistrationSubmissionViewModel.cs, src/EPR.RegulatorService.Frontend.Web/Views/RegistrationSubmissions/GrantRegistrationSubmission.cshtml
=> Implement Approve Resubmitted Data Page (496582), Redirect (496583) & Store Decision (496585)

src/EPR.RegulatorService.Frontend.Web/Views/Shared/Components/SubmissionDetails/Default.cshtml
Added flag check to display/hide submitted on time
=> [feature/496625-v2]

src/EPR.RegulatorService.Frontend.Core/Models/RegistrationSubmissions/FacadeCommonData/OrganisationRegistrationSubmissionSummaryResponse.cs, src/EPR.RegulatorService.Frontend.Core/Models/RegistrationSubmissions/FacadeCommonData/RegistrationSubmissionOrganisationDetailsResponse.cs, src/EPR.RegulatorService.Frontend.Core/Models/RegistrationSubmissions/RegistrationSubmissionOrganisationDetails.cs, src/EPR.RegulatorService.Frontend.Core/Models/RegistrationSubmissions/RegistrationSubmissionOrganisationSubmissionSummaryDetails.cs, src/EPR.RegulatorService.Frontend.Core/Models/RegistrationSubmissions/RegulatorDecisionRequest.cs, src/EPR.RegulatorService.Frontend.Web/Controllers/RegistrationSubmissions/RegistrationSubmissionsController_part.cs, src/EPR.RegulatorService.Frontend.Web/ViewModels/RegistrationSubmissions/RegistrationSubmissionDetailsViewModel.cs, src/EPR.RegulatorService.Frontend.Web/ViewModels/RegistrationSubmissions/SubmissionDetailsViewModel.cs
Changes to Add the Resubmission FileId to Regulator Decisions.
=> Add resubmissionfileid to resubmission decisions

src/EPR.RegulatorService.Frontend.Web/Views/Submissions/SubmissionDetails.cshtml
Minor to resolve the bug: Accept or reject is not working in regulator portal
=> Minor to resolve the bug: Accept or reject is not working in regulator portal

src/EPR.RegulatorService.Frontend.UnitTests/Web/Controllers/SubmissionControllerTests.cs, src/EPR.RegulatorService.Frontend.UnitTests/Web/Controllers/SubmissionDetailsTests.cs, src/EPR.RegulatorService.Frontend.Web/Controllers/Submissions/SubmissionsController_part.cs
Added code to fix POM E2E defect
=> Added code to fix POM E2E defect

src/EPR.RegulatorService.Frontend.Core/Models/AbstractSubmission.cs, src/EPR.RegulatorService.Frontend.UnitTests/Web/Controllers/SubmissionControllerTests.cs, src/EPR.RegulatorService.Frontend.UnitTests/Web/Controllers/SubmissionDetailsTests.cs, src/EPR.RegulatorService.Frontend.Web/Controllers/Submissions/SubmissionsController.cs, src/EPR.RegulatorService.Frontend.Web/Controllers/Submissions/SubmissionsController_part.cs, src/EPR.RegulatorService.Frontend.Web/Views/RegistrationSubmissions/CancelRegistrationSubmission.cshtml, src/EPR.RegulatorService.Frontend.Web/Views/RegistrationSubmissions/QueryRegistrationSubmission.cshtml, src/EPR.RegulatorService.Frontend.Web/Views/RegistrationSubmissions/RejectRegistrationSubmission.cshtml
Added code change to resolve POM offline payment issues and Accessibility issues
=> Added code change to resolve POM offline payment issues and Accessibility issues

src/EPR.RegulatorService.Frontend.UnitTests/Web/ViewComponents/PackagingCompliancePaymentDetailsViewComponentTests.cs, src/EPR.RegulatorService.Frontend.Web/Resources/SharedResources.cy.resx, src/EPR.RegulatorService.Frontend.Web/Resources/SharedResources.en.resx, src/EPR.RegulatorService.Frontend.Web/ViewComponents/Submissions/PackagingCompliancePaymentDetailsViewComponent.cs, src/EPR.RegulatorService.Frontend.Web/Views/Shared/Components/PackagingCompliancePaymentDetails/Default.cshtml
Display an appropriate message when cso member count is 0 for pom
=> Display an appropriate message when cso member count is 0 for pom into main

src/EPR.RegulatorService.Frontend.UnitTests/Web/Controllers/SubmissionControllerTests.cs, src/EPR.RegulatorService.Frontend.Web/Controllers/Submissions/SubmissionsController.cs
Minor code change to resolve POM ClearFilter issues
=> Minor code change to resolve POM ClearFilter issues

src/EPR.RegulatorService.Frontend.Core/Models/ReprocessorExporter/Registrations/RegistrationMaterialWasteLicence.cs, src/EPR.RegulatorService.Frontend.Core/Models/ReprocessorExporter/Registrations/SiteDetails.cs, src/EPR.RegulatorService.Frontend.Core/Services/ReprocessorExporter/MockedReprocessorExporterService.cs, src/EPR.RegulatorService.Frontend.UnitTests/Core/Services/ReprocessorExporter/ReprocessorExporterServiceTests.cs, src/EPR.RegulatorService.Frontend.UnitTests/Web/Controllers/ReprocessorExporter/Registrations/RegistrationsControllerTests.cs, src/EPR.RegulatorService.Frontend.UnitTests/Web/Mappings/SiteDetailsMappingProfileTests.cs, src/EPR.RegulatorService.Frontend.Web/Mappings/SiteDetailsMappingProfile.cs, src/EPR.RegulatorService.Frontend.Web/ViewModels/ReprocessorExporter/Registrations/MaterialWasteLicencesViewModel.cs, src/EPR.RegulatorService.Frontend.Web/Views/ReprocessorExporter/Registrations/MaterialWasteLicences.cshtml, src/EPR.RegulatorService.Frontend.Web/Views/ReprocessorExporter/Registrations/SamplingInspection.cshtml, src/EPR.RegulatorService.Frontend.Web/Views/ReprocessorExporter/Registrations/UkSiteDetails.cshtml
Fixed bug related to Mark as Reviewed / Queried button
=> Fixed bug related to Mark as Reviewed / Queried button

src/EPR.RegulatorService.Frontend.Web/Controllers/ReprocessorExporter/Registrations/RegistrationStatusController.cs, src/EPR.RegulatorService.Frontend.Web/ViewModels/ReprocessorExporter/Registrations/RegistrationStatus/PaymentDateViewModel.cs, src/EPR.RegulatorService.Frontend.Web/Views/ReprocessorExporter/Registrations/RegistrationStatus/PaymentReview.cshtml
Change link to button on payment review screen.
=> Bug/558374: Fix to ensure payment date is a valid four digit year.

src/EPR.RegulatorService.Frontend.UnitTests/Core/Extensions/EnumExtensionMethods.cs
Added more unit tests to resolve SQ issues
=> Added more unit tests to resolve SQ issues

src/EPR.RegulatorService.Frontend.UnitTests/Web/Controllers/ReprocessorExporter/Registrations/RegistrationStatusControllerTests.cs, src/EPR.RegulatorService.Frontend.Web/Controllers/ReprocessorExporter/Registrations/RegistrationStatusController.cs, src/EPR.RegulatorService.Frontend.Web/Views/ReprocessorExporter/Registrations/RegistrationStatus/RegistrationApplicationStatus.cshtml
Determination week - Check registration status - Revisiting the screen after duly made
=> Added determination week value

src/EPR.RegulatorService.Frontend.Web/Views/ReprocessorExporter/Registrations/SamplingInspection.cshtml
Sampling and inspection plan - accessibility errors
=> Bug - Sampling and inspection plan - accessibility errors

pipelines/ci_pipeline.yaml
[AB#616234](https://dev.azure.com/defragovuk/67a63f24-5d0d-4c35-9d23-885593eb7354/_workitems/edit/616234)
=> remove sonarqube version toggle + other tidy ups AB#616234

src/EPR.RegulatorService.Frontend.Core/EPR.RegulatorService.Frontend.Core.csproj, src/EPR.RegulatorService.Frontend.UnitTests/EPR.RegulatorService.Frontend.UnitTests.csproj, src/EPR.RegulatorService.Frontend.Web/EPR.RegulatorService.Frontend.Web.csproj
601743 - Updated packages to fix vulnerabilities
=> 601743 - Updated packages to fix vulnerabilities
